# Generated by Django 5.0.6 on 2024-07-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria_1_2_2',
            name='year',
            field=models.IntegerField(choices=[(2021, '2021-2022'), (2022, '2022-2023'), (2023, '2023-2024'), (2024, '2024-2025'), (2025, '2025-2026')]),
        ),
    ]
