# Generated by Django 5.0.7 on 2024-07-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("criteria_1", "0004_alter_criteria_1_2_2_course_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="criteria_1_2_2",
            name="year",
            field=models.IntegerField(
                choices=[
                    (2021, "June 2021 - 2022"),
                    (2022, "2022-2023"),
                    (2023, "2023-2024"),
                    (2024, "2024-2025"),
                    (2025, "2025-2026"),
                ]
            ),
        ),
    ]
